# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  redis-vector-db:
    image: research-assistant/redis-vector-db:dump
    container_name: redis-vector-db
    ports:
      - "1379:6379"
      - "1001:8001"
  
  mongodb:
    image: research-assistant/mongodb:dump
    restart: always
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      WHISPER_MODEL_SIZE: ${WHISPER_MODEL_SIZE:-base}
      WHISPER_SERVICE_PORT: ${WHISPER_SERVICE_PORT:-8765}
      MONGO_INITDB_ROOT_USERNAME: agents
      MONGO_INITDB_ROOT_PASSWORD: agents
    ports:
      - "27019:27017"
      
  # vllm-service:
  #   image: ${REGISTRY:-opea}/vllm-gaudi:${TAG:-latest}
  #   container_name: parliament-rag-vllm-gaudi-server-H4
  #   ports:
  #     - "8007:80"
  #   volumes:
  #     - ${HF_CACHE}:/.cache/huggingface/hub
  #   environment:
  #     no_proxy: ${no_proxy}
  #     http_proxy: ${http_proxy}
  #     https_proxy: ${https_proxy}
  #     HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
  #     HABANA_VISIBLE_DEVICES: 4
  #     OMPI_MCA_btl_vader_single_copy_mechanism: none
  #     VLLM_SKIP_WARMUP: true
  #     LLM_MODEL_ID: ${LLM_MODEL_ID}
  #     NUM_CARDS: 1
  #     VLLM_TORCH_PROFILER_DIR: "/mnt"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 100
  #   runtime: habana
  #   cap_add:
  #     - SYS_NICE
  #   ipc: host
  #   command: --model ${LLM_MODEL_ID} --tensor-parallel-size 1 --host 0.0.0.0 --port 80 --block-size 128 --max-num-seqs 256 --max-seq-len-to-capture 2048

    # vllm-service:
    #   image: vllm-cpu-env
    #   container_name: vllm-service
    #   ports:
    #     - "9009:8000"
    #   volumes:
    #     - ${HF_CACHE}:/root/.cache/huggingface/hub
    #   privileged: true
    #   environment:
    #     no_proxy: ${no_proxy}
    #     http_proxy: ${http_proxy}
    #     https_proxy: ${https_proxy}
    #     VLLM_USE_V1: 1
    #     VLLM_ALLOW_LONG_MAX_MODEL_LEN: 1
    #     VLLM_ENGINE_ITERATION_TIMEOUT_S: 600
    #     VLLM_CPU_KVCACHE_SPACE: 20
    #     VLLM_CPU_OMP_THREADS_BIND: "0-23"
    #     HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    #     VLLM_TORCH_PROFILER_DIR: "/mnt"
    #   cpuset: "0-23"
    #   command: --model $LLM_MODEL_ID --host 0.0.0.0 -tp 1 --dtype bfloat16
  
  tei-reranking-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    container_name: tei-reranking-server
    ports:
      - "8808:80"
    volumes:
      - ${HF_CACHE}:/data
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
    command: --model-id ${RERANK_MODEL_ID} --auto-truncate
  
  tei-embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    container_name: tei-embedding-server
    ports:
      - "6006:80"
    volumes:
      - ${HF_CACHE}:/data
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    command: --model-id ${EMBEDDING_MODEL_ID} --auto-truncate
  
  # dataprep-redis:
  #   image: ai-agents/dataprep:latest
  #   container_name: research-dataprep-redis-server
  #   depends_on:
  #     - redis-vector-db
  #     - tei-embedding-service
  #   volumes:
  #     - /mnt/hf_cache:/.cache
  #   ports:
  #     - "1006:6007"
  #   ipc: host
  #   environment:
  #     no_proxy: ${no_proxy}
  #     http_proxy: ${http_proxy}
  #     https_proxy: ${https_proxy}
  #     REDIS_URL: ${REDIS_URL}
  #     HTTP_PROXY: ${HTTP_PROXY}
  #     HTTPS_PROXY: ${HTTPS_PROXY}
  #     LOGFLAG: ${LOGFLAG}
  #     TEI_ENDPOINT: http://tei-embedding-service:80
  #     HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
  #     SERVER_HOST_IP: ${LLM_SERVER_HOST_IP}
  #     SERVER_PORT: ${LLM_SERVER_PORT}
  #   restart: unless-stopped

  retriever:
    image: research-assistant/retriever:latest
    ports:
      - "1007:7000"
    ipc: host
    depends_on:
      - redis-vector-db
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      TEI_EMBEDDING_ENDPOINT: http://tei-embedding-service:80
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped

  # groq-service:
  #   image: ai-agents-groq:latest
  #   container_name: research-groq-service
  #   ports:
  #     - "1099:8000"
  #   volumes:
  #     - /mnt/hf_cache:/root/.cache
  #   environment:
  #     no_proxy: ${no_proxy}
  #     http_proxy: ${http_proxy}
  #     https_proxy: ${https_proxy}
  #     GROQ_API_KEY: ${GROQ_API_KEY}
  #     HTTP_PROXY: ${HTTP_PROXY}
  #     HTTPS_PROXY: ${HTTPS_PROXY}
  
  backend:
    image: research-assistant/rag/backend:latest
    depends_on:
      - redis-vector-db
      - tei-embedding-service
      - retriever
      - tei-reranking-service
      # - vllm-service
    ports:
      - "5008:9000"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${SERVER_HOST_URL}
      - EMBEDDING_SERVER_HOST_IP=${EMBEDDING_SERVER_HOST_IP}
      - EMBEDDING_SERVER_PORT=${EMBEDDING_SERVER_PORT:-80}
      - RETRIEVER_SERVICE_HOST_IP=${RETRIEVER_SERVICE_HOST_IP}
      - RETRIEVER_SERVICE_PORT=${RETRIEVER_SERVICE_PORT}
      - RERANK_SERVER_HOST_IP=${RERANK_SERVER_HOST_IP}
      - RERANK_SERVER_PORT=${RERANK_SERVER_PORT:-80}
      - LLM_SERVER_HOST_IP=${LLM_SERVER_HOST_IP}
      - LLM_SERVER_PORT=${LLM_SERVER_PORT}
      - LLM_MODEL_ID=${LLM_MODEL_ID}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LOGFLAG=${LOGFLAG}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USERNAME=agents
      - MONGO_PASSWORD=agents
      - WHISPER_SERVICE_HOST_IP=${WHISPER_SERVICE_HOST_IP}
    ipc: host
    restart: always
  
  ui:
    image: research-assistant/rag/ui:latest
    depends_on:
      - backend
    ports:
      - "5009:3000"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
    restart: always

networks:
  default:
    driver: bridge
